name: Chr0m1ng Twitter Bot CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "src/configs/*.json"
        env:
          twitter.access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter.access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          twitter.api_key: ${{ secrets.TWITTER_API_KEY }}
          twitter.api_secret_key: ${{ secrets.TWITTER_API_SECRET_KEY }}
          mongo.connection_string: ${{ secrets.MONGO_CONNECTION_STRING }}
          mongo.database: ${{ secrets.MONGO_DATABASE }}
          bot.follow_triggers: ${{ secrets.BOT_FOLLOW_TRIGGERS }}

      - name: Cat settings
        run: cat "src/configs/settings.example.json"
      
      - name: Git commit
        run: git commit -am "Update settings"
      
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.0.4
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Email that you use with heroku
          heroku_email: gabrielrsantoss@icloud.com
          # The appname to use for deploying/updating
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
