# This is a basic workflow to help you get started with Actions

name: Chr0m1ng Twitter Bot CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.8
    
    - name: Pip Installer
      uses: BSFishy/pip-action@v1
    
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    
    - name: Pipenv install
      run: pipenv install
    
    - name: Set settings file env
      env: 
        SETTINGS_FILE: settings.example.json
   
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        # comma separated list of XML/JSON/YAML files in which tokens are to be substituted. Files names must be specified relative to the folder-path.
        files: ./src/configs/$SETTINGS_FILE
        twitter.access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter.access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        twitter.api_key: ${{ secrets.TWITTER_API_KEY }}
        twitter.api_key_secret: ${{ secrets.TWITTER_API_KEY_SECRET }}
        mongo.connection_string: ${{ secrets.MONGO_CONNECTION_STRING }}
        mongo.database: ${{ secrets.MONGO_DATABASE }}
        bot.follow_triggers: ${{ secrets.BOT_FOLLOW_TRIGGERS }}
